/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

import psoRunnable.Agent;
import psoRunnable.Swarm;
import static ui.Resultset.resultSet;

/**
 *
 * @author Lig37
 */
public class MainJFrame extends javax.swing.JFrame {

    public MyCanvas canvas;
    public static double elasticity = 1;
    
    //public ThreadDriver test;

    public MainJFrame() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitJPanel = new javax.swing.JSplitPane();
        jPanelControl = new javax.swing.JPanel();
        jBtnStart = new javax.swing.JButton();
        txtThreadNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPriceMin = new javax.swing.JTextField();
        txtPriceMax = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtElasticity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRevMin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jBtnStart.setText("Start To Draw");
        jBtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStartActionPerformed(evt);
            }
        });

        txtThreadNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThreadNumberActionPerformed(evt);
            }
        });

        jLabel1.setText("Number Of Threads:");

        jLabel3.setText("Elasticity:");

        jLabel4.setText("~");

        jLabel5.setText("Price range:");

        jLabel6.setText("$");

        jLabel7.setText("$");

        jLabel8.setText("Setting:");

        jLabel9.setText("Predic Revenue");

        jLabel11.setText("$");

        javax.swing.GroupLayout jPanelControlLayout = new javax.swing.GroupLayout(jPanelControl);
        jPanelControl.setLayout(jPanelControlLayout);
        jPanelControlLayout.setHorizontalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRevMin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelControlLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelControlLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlLayout.createSequentialGroup()
                        .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelControlLayout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPriceMin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPriceMax, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelControlLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtElasticity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelControlLayout.createSequentialGroup()
                        .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txtThreadNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelControlLayout.setVerticalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElasticity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThreadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPriceMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPriceMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRevMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jBtnStart)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        splitJPanel.setLeftComponent(jPanelControl);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitJPanel.setRightComponent(userProcessContainer);

        getContentPane().add(splitJPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStartActionPerformed

        //price range: 0-x && max>min
        //qty range:0-x && max> min
        //thread number: 30-50
        //elasticity:Coefficient (E); elasticity of demand	0-x
        //Relatively Elastic	1 < E < ∞
        //Unit Elastic              E = 1
        //Relatively Inelastic	0 < E < 1
        //Perfectly Inelastic	E = 0
        /////////////////////collection to store results//////////////////////////////////////////////////
        ////////////////////Validation starts//////////////////////////////////////////////////////////////                   
        if ("".equals(txtThreadNumber.getText())) {
            JOptionPane.showMessageDialog(null, "Plese enter how many Threads of Swarm do you want to draw", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Integer.valueOf(txtThreadNumber.getText()) < 30 || Integer.valueOf(txtThreadNumber.getText()) > 50) {
            JOptionPane.showMessageDialog(null, "The number of Thread has to between the range of 30 to 50", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if ("".equals(txtPriceMin.getText()) || "".equals(txtPriceMax.getText())) {
            JOptionPane.showMessageDialog(null, "Plese enter the price range for your product", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        else if (Double.valueOf(txtPriceMin.getText()) >50 || Double.valueOf(txtPriceMin.getText())< 20){
            JOptionPane.showMessageDialog(null, "Plese enter a valid price range for your product", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        else if (Double.valueOf(txtPriceMin.getText()) > Double.valueOf(txtPriceMax.getText()) || Double.valueOf(txtPriceMin.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "Plese enter a valid price range for your product", "Warning", JOptionPane.WARNING_MESSAGE);
        } //        else if (Double.valueOf(txtRevMin.getText())>Double.valueOf(txtRevMax.getText())||Double.valueOf(txtPriceMin.getText())<0){
        //            JOptionPane.showMessageDialog(null,"Plese enter a valid price range for your product","Warning",JOptionPane.WARNING_MESSAGE);
        //        }
        else if (Double.valueOf(txtElasticity.getText()).equals("") || Double.valueOf(txtElasticity.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "Plese enter a valid elasticity for your product", "Warning", JOptionPane.WARNING_MESSAGE);
        } //done with validation and start with creating threads
        else {
            int threadNumber = Integer.valueOf(txtThreadNumber.getText());
            double priceMin = Double.valueOf(txtPriceMin.getText());
            double priceMax = Double.valueOf(txtPriceMax.getText());
            double estimateRev = Double.valueOf(txtRevMin.getText());
            elasticity = Double.valueOf(txtElasticity.getText());

            MyCanvas canvas = new MyCanvas();
            canvas.setSize(1024,1024);
            splitJPanel.setRightComponent(canvas);
            
             //int SWARM_SIZE,double estimateRev, double LOC_Y_LOW,double LOC_Y_HIGH
                Swarm swarm = new Swarm(threadNumber,estimateRev,priceMin,priceMax);
               
                //give value to resultSet so other classes could know value
                for(int i = 0; i<swarm.getMyRunnable().size();i++){
                resultSet.add(swarm.getMyRunnable().get(i));
                }
                //init thread
                for(int x = 0; x <swarm.getMyRunnable().size();x++){
                    Agent a = swarm.getMyRunnable().get(x);
                    a.run();
                    
                    System.out.println("thread start" + a.getAgentID());
                }
     

        }


    }//GEN-LAST:event_jBtnStartActionPerformed

    private void txtThreadNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThreadNumberActionPerformed
        //data validation for txtThreadNumber, input can only be integers
        txtThreadNumber.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    return;
                } else {
                    e.consume();
                    JOptionPane.showMessageDialog(null, "Plese enter number only", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThreadNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JSplitPane splitJPanel;
    private javax.swing.JTextField txtElasticity;
    private javax.swing.JTextField txtPriceMax;
    private javax.swing.JTextField txtPriceMin;
    private javax.swing.JTextField txtRevMin;
    private javax.swing.JTextField txtThreadNumber;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
